# PHP-FPM configuration Production.
php_default_version_debian: "7.4"
php_memory_limit: "512M"
php_max_input_vars: "250"
php_date_timezone: "UTC"
php_expose_php: "Off"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_enable_apc: true
php_apc_enable_cli: true
php_apc_shm_size: "64M"
php_enablerepo: "remi-php74,epel"
php_packages_state: "installed"
php_enable_webserver: false
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_fpm_listen: "9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 1000
php_fpm_pm_start_servers: 45
php_fpm_pm_min_spare_servers: 45
php_fpm_pm_max_spare_servers: 90
php_fpm_pool_user: "nginx"
php_fpm_pool_group: "nginx"
php_short_open_tag: false

php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_display_errors: "Off"
php_display_startup_errors: "Off"

# The executable to run when calling PHP from the command line.
php_executable: "php"
#
# PHP settings used by geerlingguy.php
#
php_packages:
  - php-devel
  - php-common
  - php-pecl-apcu
  - php-pecl-zip
  - php-pear
  - php-xml
  - php-dom
  - php-mcrypt
  - php-gd
  - php-mbstring
  - php-bcmath
  - php-igbinary
  - php-cli
  - php-curl
  - php-mysql
  - php-fpm
  - php-pecl-zendopcache