---
#
# Ansible galaxy requirements file
#
# Basic Usage : http://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html
# Awesome Voodoo-fu : https://www.jeffgeerling.com/blog/2017/patching-or-using-forked-version-ansible-galaxy-role
#
# Update all dependencies with : ansible-galaxy install -r requirements.yml --force
#

- src: yatesr.timezone
- src: geerlingguy.composer
- src: geerlingguy.nginx
- src: geerlingguy.php
- src: geerlingguy.pip
- src: geerlingguy.supervisor
- src: geerlingguy.mysql
- src: geerlingguy.redis
- src: geerlingguy.firewall
- src: geerlingguy.mysql
- src: geerlingguy.repo-remi
- src: geerlingguy.repo-epel
- src: ontic.logrotate
- src: resmo.ntp
- src: https://github.com/geerlingguy/ansible-role-php-versions
  name: ansible-role-php-versions