version: '3.7'

networks:
  prod-stack:

services:
  # Master
  master:
    image: ${APP_BASE}/master
    build:
      dockerfile: python.dockerfile
      context: ${PWD}/docker/master     
    container_name: ansible
    environment:
      - APP_ENV=${APP_ENV}
      - SSH_AUTH_SOCK="/ssh-agent"
      - ANSIBLE_CONFIG="/etc/ansible/ansible.cfg"
    volumes:
      - ${PWD}/code:/work
      - ${PWD}/docker/master/roles:/etc/ansible/roles
      - ${PWD}/docker/master/ansible.cfg:/etc/ansible/ansible.cfg
      - ${PWD}/docker/keys/node_user/id_rsa:/root/.ssh/id_rsa
      - ${SSH_AUTH_SOCK}:/ssh-agent
    tty: true
    secrets:
      - node_user_id_rsa   
    command: ["bash"] 
    networks:
      - prod-stack

  # Web Host 1 
  node1:
    image: ${APP_BASE}/${APP_NODE}
    build:
      dockerfile: ${APP_NODE}.dockerfile
      context: ${PWD}/docker/worker
    container_name: node1
    privileged: true
    volumes:
      - ${PWD}/docker/keys/node_user/id_rsa.pub:/home/node_user/.ssh/authorized_keys
    tty: true
    networks:
      prod-stack:
        aliases: 
          - app.prod.host1

  # Web Host 2
  node2:
    image: ${APP_BASE}/${APP_NODE}
    build:
      dockerfile: ${APP_NODE}.dockerfile
      context: ${PWD}/docker/worker
    container_name: node2
    privileged: true
    volumes:
      - ${PWD}/docker/keys/node_user/id_rsa.pub:/home/node_user/.ssh/authorized_keys
    tty: true
    networks:
      prod-stack:
        aliases: 
          - app.prod.host2

  # Mysql Host
  node3:
    image: ${APP_BASE}/${APP_NODE}
    build:
      dockerfile: ${APP_NODE}.dockerfile
      context: ${PWD}/docker/worker
    container_name: node3
    privileged: true
    volumes:
      - ${PWD}/docker/keys/node_user/id_rsa.pub:/home/node_user/.ssh/authorized_keys
    tty: true
    networks:
      prod-stack:
        aliases: 
          - app.prod.db1           

  # Redis Host
  node4:
    image: ${APP_BASE}/${APP_NODE}
    build:
      dockerfile: ${APP_NODE}.dockerfile
      context: ${PWD}/docker/worker
    container_name: node4
    privileged: true
    volumes:
      - ${PWD}/docker/keys/node_user/id_rsa.pub:/home/node_user/.ssh/authorized_keys
    tty: true
    networks:
      prod-stack:
        aliases: 
          - app.prod.redis
         
  # Mail Host
  node5:
    image: ${APP_BASE}/${APP_NODE}
    build:
      dockerfile: ${APP_NODE}.dockerfile
      context: ${PWD}/docker/worker
    container_name: node5
    privileged: true
    volumes:
      - ${PWD}/docker/keys/node_user/id_rsa.pub:/home/node_user/.ssh/authorized_keys
    tty: true
    networks:
      prod-stack:
        aliases: 
          - app.prod.mail

secrets:
  node_user_id_rsa:
    file: ${PWD}/docker/keys/node_user/id_rsa  