---
#
# Configure php & php-fpm
#
- hosts: web
  vars_files:
    - /work/inventories/vars/production.yml
  become: yes

  roles:
    #- ansible-role-php-versions
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.redis

  # Send system email someplace sane by re-pointing the
  tasks:
    - name: Create PHP FMP configuration directory
      file:
        path: /etc/php-fpm.d
        state: directory
    - name: Copy PHP configuraitons files
      copy: src={{ ConfigurationFilesDir }}/{{ item }} dest=/etc/php-fpm.d/{{ item }} mode=0600 owner=root group=root
      with_items: "{{ ConfigurationFiles }}"
      
    - name: Add config to php-fpm pool
      blockinfile:
        dest: /etc/php-fpm.d/www.conf
        marker: ; ANSIBLE MANAGED BLOCK
        block: |
          pm.status_path = /status
          ping.path = /ping
          ping.response = pong
          access.log = /var/log/php-fpm/$pool.access.log
          access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"
