---
#
# SSLCertificate files used by udify 
# Note : Currently self signed certs - Update when we've purchased real ones & move to Vault.
#
SSLCertificateSrcDir: /work/files/ssl
SSLCertificateFiles:
- self.crt
- self.key
- self.crt

#
# Logrotate config - used by logrotate role
#
logrotate_config_files:
- name: 'syslog'
  paths:
    - '/var/log/local1'
    - '/var/log/local2'
    - '/var/log/local3'
    - '/var/log/local4'
    - '/var/log/local5'
    - '/var/log/local6'
    - '/var/log/local7'
    - '/var/log/cron'
    - '/var/log/maillog'
    - '/var/log/secure'
    - '/var/log/spooler'
    - '/var/log/messages'
    - '/var/log/boot'
  options:
    - 'compress'
    - 'create 0640 nobody adm'
    - 'daily'
    - 'delaycompress'
    - 'missingok'
    - 'notifempty'
    - 'rotate 7'
    - 'sharedscripts'
  scripts:
    postrotate: '/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
- name: 'nginx'
  paths:
    - '/var/log/nginx/*.log'
  options:
    - 'compress'
    - 'create 0640 nginx adm'
    - 'daily'
    - 'delaycompress'
    - 'missingok'
    - 'notifempty'
    - 'rotate 7'
    - 'sharedscripts'
  scripts:
    postrotate: '[ -s /var/run/nginx.pid ] && kill -USR1 `cat /var/run/nginx.pid`'

#
# PHP settings used by geerlingguy.php
#
php_packages:
- php-devel
- php-common
- php-pecl-apcu
- php-pecl-zip
- php-pear
- php-xml
- php-dom
- php-mcrypt
- php-gd
- php-mbstring
- php-bcmath
- php-igbinary
- php-cli
- php-curl
- php-mysql
- php-fpm
- php-pecl-zendopcache

php_memory_limit: "512M"
php_max_input_vars: "250"
php_date_timezone: "UTC"
php_expose_php: "Off"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_enable_apc: true
php_apc_enable_cli: true
php_apc_shm_size: "64M"
php_enablerepo: "remi-php72,epel"
php_packages_state: "installed"
php_enable_webserver: false
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_fpm_listen: "9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 1000
php_fpm_pm_start_servers: 45
php_fpm_pm_min_spare_servers: 45
php_fpm_pm_max_spare_servers: 90
php_fpm_pool_user: "nginx"
php_fpm_pool_group: "nginx"
php_short_open_tag: false

#
# /etc/hosts updates for local services - used by bertvv.hosts
#
hosts_entries:
- name: www-db
  ip: "{{ db_mysql_master_host }}"
- name: portal-db
  ip: "{{ db_mysql_master_host }}"

#
# Deployment Keys
#

deploy_keys:
- publickey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC22uNlzj/g5g+4lHtqmnBP0q5iSHnrhlO9ohYWmyCRPR+9g0dO3nrLGsIDhi4VjS3HfazS3R9yNvGvjnU/ygjOq8BIxaecNP7VRzhBjfHhq+bzGKXM+eXzFd9WkDdxZ4YZf6Kn8aAK1gmrOY0KVpxLR9SnEuch30hTCPZZvSgqbF/A0v4rtFQFdHftBPKNXW09HirPMDD6l+CjIiE9YIBE6SLiYIyVUZ/g8FdbBpGfIIeGejO9grogv0CG5eHDz654HIcruqxkxedGAO0GzGHGn2xwE3txLy/Q2PgxztOyMKobo0B1NyyPBxbTw5aammjpf7HG4af0SkvbgBSClREb DeployHQ.com Key for www"
- publickey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCt3MdL66nVKtaHTzHB56XNR35n5A3F4ETbu+8Ac+5DRlk3W0x0kArJHm2iEY/NcIjMn+zyN/SO+5kLfSRPl5//6YNBnH8Ditc6JjNhsUMZKPVtKTp8f+CwYRsfdoWyzCNRT/wWkW9J3ANtnL0rByBQVNoWVFDuWDR8tvy9g0SI8etqJfygyB/ru5F82W3f1wg8vbcvjQSkybdrSWeIp57DPMPF9uBoW75g1D2EHGUY4wGyGfb0qLyRnTqYH03uaB1EOsq7UlBXLiM999a+XEB5SOq9dytElL8QBABRDR9O4u2lwXzUHtQmicu+mv/fsYy+rNYzvhK6rWFg0xDMxv+b DeployHQ.com Key for my"
- publickey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSFTrpHTyVSLLJrXLK/5G8ksoXq2msUTe1ZskRuy1CZZf6MBVShSqFSvYEyVLnIcFxjAd5c9pnR/1Cc45EvQr1M7F5mNvLfrFPLOw0xm78TL9qUCJ3uDfH4eD8ny9l9X6Wek0FZYv8QRIfgOMXd9ioyZoQ69sZMeHQDNuLffl/jSNIXyDKmFqGNIvW+pqUrCLmHM41l2zUhWjGeiS1VnwiuYSZleB3O5JCOFY2f12em7V1ZwpuXEn7CMuBp4k4+vIKcv5//9qsIogYhvt372+SLdvU97FfBuG21+otpu5gVlKmEVYf4z2/TSzmEBLB8tjGJ+hMAMs/sLrDBlDBenJj DeployHQ.com Key for udify-wp-theme"

#
# Nginx Settings - used by geerlingguy.nginx
# Tuned with : https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
#
nginx_user: nginx
nginx_remove_default_vhost: true
nginx_pidfile: /var/run/nginx.pid
nginx_keepalive_timeout: "15"
nginx_keepalive_requests: "100"
nginx_client_max_body_size: "24m"
nginx_access_log: "/var/log/nginx/access.log main"

nginx_extra_http_options: |
  limit_req_zone      $request_uri zone=one:100m rate=75r/s;
  limit_req_status    429;
  limit_req_log_level warn;
  proxy_buffering    off;
  proxy_set_header   X-Real-IP $remote_addr;
  proxy_set_header   X-Scheme $scheme;
  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header   Host $http_host;
  ssl_session_cache  shared:SSL:10m;
  ssl_session_timeout 10m;
  gzip on;
  gzip_http_version 1.1;
  gzip_proxied any;
  gzip_types text/plain text/css text/xml text/javascript text/js application/javascript application/xml+rss;
  gzip_buffers 16 8k;
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";  

# Define vhosts in group specific files.
#nginx_vhosts: 

#
# Where system created email gets sent to
#
root_email_alias: hostmaster@adventus.io

#
# Mysql Wordpress Database Config
#

mysql_max_binlog_size: "100M"
mysql_binlog_format: "ROW"
mysql_expire_logs_days: "10"
mysql_replication_master: '139.180.216.48'
mysql_root_password: "L2bg9ZbN)v|9"
mysql_databases:
  - name: portal
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: portal
    host: "%"
    password: "PO(bz10-ARRJtok"
    priv: "portal.*:ALL"

mysql_replication_user:
    name: replicator
    host: "%"
    password: "388aAS^e88F!d#gx"

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "_"
    root: "/var/www/adventus.io/current/public"
    index: "index.php index.html index.htm"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "adventus.io.conf"
    extra_parameters: |
      listen 443 ssl http2 default_server;
      location /nginx_status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
      }
      location /oauth {
        auth_basic off;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param TRUE-CLIENT-IP $http_true_client_ip;
        fastcgi_read_timeout 600;          
      }
      location /api/institution {
        auth_basic off;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param TRUE-CLIENT-IP $http_true_client_ip;
        fastcgi_read_timeout 600;          
      }
      location ^~ /offerquestions {
        auth_basic off;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param TRUE-CLIENT-IP $http_true_client_ip;
        fastcgi_read_timeout 600;          
        fastcgi_buffers 16 16k; 
        fastcgi_buffer_size 32k;
      }
      location / {                                       
        auth_basic           "Coming Soon";
        auth_basic_user_file /var/www/.htpasswd;
        try_files $uri $uri/ /index.php?$args;
      }
      location ~ \.php$ {
        auth_basic           "Coming Soon";
        auth_basic_user_file /var/www/.htpasswd;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param TRUE-CLIENT-IP $http_true_client_ip;
        fastcgi_read_timeout 600;
        fastcgi_buffers 16 16k; 
        fastcgi_buffer_size 32k;
      }
      ssl_certificate     /etc/ssl/www/adventus_io.crt;
      ssl_certificate_key /etc/ssl/www/adventus_io.key;
      ssl_dhparam       /etc/ssl/www/dhparam.pem;
      ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
